mail if front down and emptying log daily

diff --git a/cron/master b/cron/master
--- a/cron/master
+++ b/cron/master
@@ -25,6 +25,23 @@ createLogFile()
         fi
 }
 
+isFrontUp()
+{
+	HTTP_CODE=$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' http://front-wawamania.rhcloud.com)
+	return $HTTP_CODE
+}
+
+mailThatFrontIsDown()
+{
+	DATE=$(date)
+	curl -s --user 'api:key-085qdf4zyijqycd8jezv3pzknmxf99m8' \
+    	https://api.mailgun.net/v2/sandboxf2d5d32035db4032af78a2c69fb07084.mailgun.org/messages \
+    	-F from='Mailgun Sandbox <postmaster@sandboxf2d5d32035db4032af78a2c69fb07084.mailgun.org>' \
+    	-F to='Duke <kevin.langles@gmail.com>'\
+    	-F subject='Production down' \
+    	-F text='Cron message : server http://front-wawamania.rhcloud.com down !'
+}
+
 APP_REPO=~/app-root/runtime/repo/
 MODULES_REPO=$APP_REPO/modules/
 
@@ -126,12 +143,27 @@ while [[ k -lt i ]]; do
 			# --hourly
 			echo "Calling (hourly) : node $INIT_PATH ${modules[$k]} >> $LOG_REPO/${logs[$k]} &"
 			node $INIT_PATH ${modules[$k]} >> $LOG_REPO/${logs[$k]} &
+			# check if front is up or down
+			echo "Checking if front is still up..."
+			isFrontUp
+			if [[ $? -ne 200 ]]; then
+				echo "Error : front didn't send 200 status code, emailing admin..."
+				mailThatFrontIsDown
+			else
+				echo "Front sent 200 status code"
+			fi
 		fi
 	elif [[ ${crony[$k]} == ${CRON_POSSIBILITIES[3]} ]]; then
 		if [[ $(date +%H) -eq 0 ]] && [[ $(date +%M) -eq 0 ]]; then
 			# --daily
 			echo "Calling (daily) : node $INIT_PATH ${modules[$k]} >> $LOG_REPO/${logs[$k]} &"
 			node $INIT_PATH ${modules[$k]} >> $LOG_REPO/${logs[$k]} &
+			# Emptying log files
+			echo "Emptying log files..."
+			echo > $CRON_LOG
+			for log in ${logs[@]}; do
+        			echo > $LOG_REPO/$log
+			done
 		fi
 	fi
 	let k=k+1
